### ISSUE TITLE
Steam Controller crashing after waking from sleep

### ISSUE THREAD

**Issue by ahzaidi** [ayufan/steam-deck-tools#16]
This issue also happened on SWICD, but it's a lot more frequent with the Steam Deck Controller software. Any ideas?

**Comment by ahzaidi** [comment]
Application: SteamController.exe
CoreCLR Version: 6.0.1122.52304
.NET Version: 6.0.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully.
   at Nefarius.ViGEm.Client.ViGEmTarget.Connect()
   at Nefarius.ViGEm.Client.Targets.Xbox360Controller.Connect()
   at SteamController.Devices.Xbox360Controller.SetConnected(Boolean wantsConnected) in D:\a\steam-deck-tools\steam-deck-tools\SteamController\Devices\Xbox360Controller.cs:line 73
   at SteamController.Devices.Xbox360Controller.Update() in D:\a\steam-deck-tools\steam-deck-tools\SteamController\Devices\Xbox360Controller.cs:line 127
   at SteamController.Context.Update() in D:\a\steam-deck-tools\steam-deck-tools\SteamController\Context.cs:line 129
   at SteamController.Context.ThreadLoop(Object obj) in D:\a\steam-deck-tools\steam-deck-tools\SteamController\ContextThread.cs:line 43
   at System.Threading.Thread.StartCallback()
