### ISSUE TITLE
PowerControl.exe wont open

### ISSUE THREAD

**Issue by DARTH-BARSI** [ayufan/steam-deck-tools#185]
Log Name:      Application
Source:        .NET Runtime
Date:          14/06/2024 11:15:35
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      SteamDeck
Description:
Application: PowerControl.exe
CoreCLR Version: 6.0.3124.26714
.NET Version: 6.0.31
Description: The process was terminated due to an unhandled exception.
Exception Info: hidapi.HidDeviceInvalidException: The device is invalid. Cannot perform actions on invalid device. Make sure it was opened properly and is still available.
   at hidapi.HidDevice.ThrowIfDeviceInvalid()
   at hidapi.HidDevice.Read(Byte[] buffer, Int32 timeout)
   at hidapi.HidDevice.ReadLoop()
   at System.Threading.Thread.StartCallback()

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-06-14T10:15:35.3520684Z" />
    <EventRecordID>623</EventRecordID>
    <Correlation />
    <Execution ProcessID="6240" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>SteamDeck</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: PowerControl.exe
CoreCLR Version: 6.0.3124.26714
.NET Version: 6.0.31
Description: The process was terminated due to an unhandled exception.
Exception Info: hidapi.HidDeviceInvalidException: The device is invalid. Cannot perform actions on invalid device. Make sure it was opened properly and is still available.
   at hidapi.HidDevice.ThrowIfDeviceInvalid()
   at hidapi.HidDevice.Read(Byte[] buffer, Int32 timeout)
   at hidapi.HidDevice.ReadLoop()
   at System.Threading.Thread.StartCallback()
</Data>
  </EventData>
</Event>

**Comment by jes0411** [comment]
It seems you have hidhide installed. 
It's needed to add the 4 exe's of steam deck tools to exceptions on hidhide or uninstall hidhide for it to work properly
